Repository pagopa/pagopa-payment-wallet-cdc-service, pull requests merged in 2024-10, with the labels that each got.

#1 chore: [CHK-3275] init
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  .gitignore
  .java-version
  .pre-commit-config.yaml
  CODEOWNERS
  HELP.md
  build.gradle.kts
  eclipse-style.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/it/pagopa/wallet/PagopaPaymentWalletCdcServiceApplication.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/PagopaPaymentWalletCdcServiceApplicationTests.kt
Labels: skip_release

#3 chore: CHK-3283 update init configuration
  build.gradle.kts
  gradle.lockfile
  src/main/resources/banner.txt
  src/main/resources/logback-spring.xml
Labels: size/small

#2 feat: [CHK-3282] Added localenv setup
  .env.local
  Dockerfile
  README.md
  azurite/Dockerfile
  azurite/create-queues.sh
  build.gradle.kts
  docker-compose.yml
  docker/README.md
  docker/config/mongo/mongo-express.env
  docker/config/mongo/mongodb.env
  docker/run_docker.sh
Labels: size/large

#4 chore: CHK-3276 add cr/cd pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/large

#6 Chk 3279 change stream
  .devops/code-review-pipelines.yml
  Dockerfile
  README.md
  build.gradle.kts
  docker-compose.yml
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/Chart.yaml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/PagopaPaymentWalletCdcServiceApplication.kt
  src/main/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStream.kt
  src/main/kotlin/it/pagopa/wallet/config/ChangeStreamOptionsConfig.kt
  src/main/kotlin/it/pagopa/wallet/config/RetrySendPolicyConfig.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/PagopaPaymentWalletCdcServiceApplicationTests.kt
  src/test/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStreamTest.kt
  src/test/resources/application-test.properties
Labels: size/small

#7 fix: CHK-3276 Add task for semantic versioning
  build.gradle.kts
  gradle.propetries
Labels: size/small

#10 chore: CHK-3276 semantic versioning check
  .github/workflows/check_pr.yml
Labels: size/small, ignore-for-release, skip-release

#9 Feat [CHK-3308] added implementation send event on queue using producer
  .env.local
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStream.kt
  src/main/kotlin/it/pagopa/wallet/client/WalletQueueClient.kt
  src/main/kotlin/it/pagopa/wallet/config/AzureStorageConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/config/properties/CdcQueueConfig.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletPaymentCDCEventDispatcherService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStreamTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletPaymentCDCEventDispatcherServiceTest.kt
  src/test/resources/application-test.properties
Labels: size/small, minor, chart-minor

#13 chore(producer): change content and format of data written to queue
  src/main/kotlin/it/pagopa/wallet/client/WalletQueueClient.kt
  src/main/kotlin/it/pagopa/wallet/common/QueueEvent.kt
Labels: size/small, minor, chart-minor

#12 Feat: [CHK-3309] Added integration tests inside code review pipeline
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  Dockerfile
  api-tests/wallet_local_cdc.collection.tests.json
  api-tests/wallet_local_cdc.environment.json
  azurite/create-queues.sh
  docker-compose.yml
  docker/config/mongo/mongo-express.env
  docker/config/wallet/Dockerfile.wallet
  docker/config/wallet/wallet.env
Labels: size/large, minor, chart-minor

#14 chore(producer): refactor the object type serialized to queue
  src/main/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStream.kt
  src/main/kotlin/it/pagopa/wallet/client/WalletQueueClient.kt
  src/main/kotlin/it/pagopa/wallet/common/QueueEvent.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletPaymentCDCEventDispatcherService.kt
  src/test/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStreamTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletPaymentCDCEventDispatcherServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/ChangeStreamDocumentUtil.kt
Labels: size/small, minor, chart-minor

#15 chore: CGK-3334 local env with mongo resplica
  .devops/code-review-pipelines.yml
  api-tests/wallet_local_cdc.collection.tests.json
  api-tests/wallet_local_cdc.environment.json
  docker-compose.yml
  docker-local/azurite/Dockerfile
  docker-local/azurite/create-queues.sh
  docker-local/mongo/mongo-express.env
  docker-local/mongo/mongodb.env
  docker-local/wallet-cdc/application.properties
  docker-local/wallet-cdc/wallet-cdc.env
  docker-local/wallet-events-producer-testing/Dockerfile
  docker-local/wallet-events-producer-testing/app.js
  docker-local/wallet-events-producer-testing/data.json
  docker-local/wallet-events-producer-testing/package.json
  docker/README.md
  docker/config/mongo/mongo-express.env
  docker/config/mongo/mongodb.env
  docker/config/wallet/Dockerfile.wallet
  docker/config/wallet/wallet.env
  docker/run_docker.sh
Labels: size/large, ignore-for-release, skip-release

#16 [CHK-3502] feat(stream): add retry in case connection to DB drops
  .env.local
  README.md
  docker-local/wallet-cdc/application.properties
  docker-local/wallet-cdc/wallet-cdc.env
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/PagopaPaymentWalletCdcServiceApplication.kt
  src/main/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStream.kt
  src/main/kotlin/it/pagopa/wallet/config/properties/RetryStreamPolicyConfig.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStreamTest.kt
  src/test/resources/application-test.properties
Labels: size/small, minor, chart-minor
