Repository pagopa/pagopa-payment-wallet-cdc-service, pull requests merged in 2024-12, with the labels that each got.

#22 Feat [CHK-3580] Added automated tests for CDC flow
  .devops/deploy-pipelines.yml
  docker-local/wallet-cdc/application.properties
Labels: size/small, minor, chart-minor

#19 feat: add prod helm values and deployment pipeline stages
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/large, minor, chart-minor

#23 [CHK-3621] feat(lock): add locking by event
  .env.local
  README.md
  build.gradle.kts
  docker-compose.yml
  docker-local/wallet-cdc/application.properties
  docker-local/wallet-cdc/wallet-cdc.env
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/PagopaPaymentWalletCdcServiceApplication.kt
  src/main/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStream.kt
  src/main/kotlin/it/pagopa/wallet/config/properties/RedisJobLockPolicyConfig.kt
  src/main/kotlin/it/pagopa/wallet/exceptions/LockException.kt
  src/main/kotlin/it/pagopa/wallet/exceptions/LockNotAcquiredException.kt
  src/main/kotlin/it/pagopa/wallet/services/CdcLockService.kt
  src/main/resources/application.properties
  src/main/resources/redisson.yaml
  src/test/kotlin/it/pagopa/wallet/PagopaPaymentWalletCdcServiceApplicationTests.kt
  src/test/kotlin/it/pagopa/wallet/cdc/PaymentWalletsLogEventsStreamTest.kt
  src/test/kotlin/it/pagopa/wallet/services/CdcLockServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/ChangeStreamDocumentUtil.kt
  src/test/resources/application-test.properties
Labels: size/small, minor, chart-minor

#24 [CHK-3612] chore(config): scale up prod env config and enable autoscaling
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch
